---
name: Build Sample
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - 'docs/Sample/*.md'
      - 'docs/Sample/*.order'
      - 'docs/Sample/.attachments/**'
  push:
    paths:
      - 'docs/Sample/*.md'
      - 'docs/Sample/*.order'
      - 'docs/Sample/.attachments/**'

jobs:
  pdf:
    name: Build PDF
    uses: innofactororg/ghw-markdown-convert/.github/workflows/build-documentation.yml@main
    secrets: inherit
    with:
      OrderFile: Sample/document.order
      OutFile: Sample.pdf
      MetadataFile: templates/azure-document.yaml
      Template: templates/azure-document.tex
      Title: Sample
      Subtitle: Document
      DocsRootFolder: docs
      BuildBranch: main
      DefaultAuthor: Innofactor
      DefaultDescription: Initial draft
      ForceDefault: false
